export enum LogAction {
    PROJECT_CREATED = 'PROJECT_CREATED',
    PROJECT_UPDATED = 'PROJECT_UPDATED',
    PROJECT_DELETED = 'PROJECT_DELETED',

    //WORKSPACE
    WORKSPACE_CREATED = 'WORKSPACE_CREATED',
    WORKSPACE_UPDATED = 'WORKSPACE_UPDATED',
    WORKSPACE_DELETED = 'WORKSPACE_DELETED',
    WORKSPACE_ADD_MEMBER = 'WORKSPACE_ADD_MEMBER',
    WORKSPACE_UPDATE_MEMBER_ROLE = 'WORKSPACE_UPDATE_MEMBER_ROLE',
    WORKSPACE_REMOVE_MEMBER = 'WORKSPACE_REMOVE_MEMBER',
    WORKSPACE_LEAVE = 'WORKSPACE_LEAVE',
    
    TASK_COMPLETED = 'TASK_COMPLETED',
  }
  